[package]
name = "odilia-tts"
version = "0.0.1"
authors = ["Michael Connor Buchan <mikey@blindcomputing.org>", "Tait Hoyem <tait@tait.tech>", "Alberto Tirla <albertotirla@gmail.com>"]
description = "Text to speech subsystem for the Odilia screen reader."
license = "gpl-3" # Not gpl-3-or-later
repository = "https://github.com/odilia-app/odilia"
homepage = "https://odilia.app"
keywords = ["accessibility", "a11y", "tts", "speech-dispatcher", "linux"]
categories = ["accessibility", "api-bindings"]
edition = "2021"
publish = false

[dependencies]
